# Reviewers automatically added for changes to Armando's portfolio
'aroquev/**/*.*':
  - pamelalozano16
  - thefredo1000

# Reviewers automatically added for changes to Rodrigo's portfolio
'ayup/**/*.*':
  - aroquev00
  - pamelalozano16

# Reviewers automatically added for changes to Pamela's portfolio
'pamelalozano/**/*.*':
  - aroquev00
  - thefredo1000
