steps:
  # Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']
  # Run JS tests
  - name: node
    entrypoint: npm
    args: ['test']
  # Build Maven project
  - name: maven
    entrypoint: mvn
    args: ['-f', './', 'package']
