steps:
  - name: maven
    entrypoint: mvn
    args: ['-f', './pamelalozano', 'package']
  - name: maven
    entrypoint: mvn
    args: ['-f', './aroquev/project', 'package']
  - name: maven
    entrypoint: mvn
    args: ['-f', './ayup/portfolio', 'package']

