name: LGTM GIF
on:
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LGTM Reaction
        uses: micnncim/action-lgtm-reaction@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_TOKEN }}
        with:
          trigger: '["(?i)^lgtm$"]'
          overide: true # [sic]
          source: 'giphy'
